- hosts: all
  gather_facts: yes
  remote_user: networkmon
  roles:
    - general
    - graphite
    - wifi

  handlers:
    - name: Restart collectd
      become: yes
      become_user: root
      command: systemctl restart collectd

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted enabled=yes

  # Restarts the network as required
  handlers:
    - name: restart networking
      service: name=networking state=restarted
